myblog/blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.homepage),
    url(r'^post/(?P<pk>[0-9]+)/$', views.showpost, name='showpost'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
 ]

myblog/comments/urls.py
from django.conf.urls import url

from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
]

myblog/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

myblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags

import markdown


class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    abstract = models.CharField(max_length=200, blank=True)
    created_time = models.DateTimeField(default=timezone.now)
    modified_time = models.DateTimeField(default=timezone.now)

    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created_time',)

    def get_absolute_url(self):
        return reverse('blog:showpost', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.abstract:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ])
            self.abstract = strip_tags(md.convert(self.text))[:54]

        super(Article, self).save(*args, **kwargs)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

myblog/comments/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Article')

    def __str__(self):
        return self.text[:20]

myblog/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass

myblog/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']

myblog/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from .models import Article, Category
from comments.forms import CommentForm


import urllib.request
import json
import markdown

url = 'http://open.iciba.com/dsapi'
page = urllib.request.urlopen(url).read()
data = page.decode("UTF-8")

data_dict = json.loads(data)
Qoute = data_dict['content']


def homepage(request):
    posts = Article.objects.all()
    now = datetime.now()
    qoute = Qoute
    return render(request, 'index.html', locals())


def showpost(request, pk):
    qoute = Qoute
    post = get_object_or_404(Article, pk=pk)
    post.increase_views()
    post.text = markdown.markdown(post.text,
                                  extensions=[
                                      'markdown.extensions.extra',       # 本身包含很多拓展
                                      'markdown.extensions.codehilite',  # 语法高亮拓展
                                      'markdown.extensions.toc',         # 允许我们自动生成目录
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'post.html', locals())


def archives(request, year, month):
    qoute = Qoute
    archives_lists = Article.objects.filter(created_time__year=year,
                                       created_time__month=month
                                       )
    return render(request, 'index.html', locals())


def category(request, pk):
    qoute = Qoute
    cate = get_object_or_404(Category, pk=pk)
    category_lists = Article.objects.filter(category=cate)
    return render(request, 'index.html', locals())

myblog/comments/views.py
# *-* coding:utf8 *-*
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Article
from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    post = get_object_or_404(Article, pk=post_pk)
    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
            # return render(request, './post.html')
        else:
            comment_list = Comment.post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, './post.html', context=context)
    return redirect(post)
# render(req,'df_user/login.html',context_instance=RequestContext(req))。

myblog/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

def register(request):
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/')
    else:
        form = RegisterForm()
        return render(request, 'users/register.html', context={'form': form, 'next': redirect_to})

myblog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{%  static 'css/highlights/github.css' %}">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</head>
<body>
    <span id="top" ></span>

    <div class="container-fluid">
        {% include 'header.html' %}
        <div class="row">
            <div class="col-sm-4 col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>    Skyge的博客   </h3>
                    </div>
                    <div class="panel-body">
                        <div class="list-group">
                            <a href="/" class="list-group-item">首页</a>
                        </div>
                        <div class="widget widget-recent-posts">
                            <h3 class="widget-title">最新文章</h3>
                                {% get_recent_posts as recent_post_list %}
                                <ul>
                                    {% for post in recent_post_list %}
                                    <li>
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </li>
                                    {% empty %}
                                        暂无文章！
                                    {% endfor %}
                                </ul>
                        </div>
                        <div class="widget widget-archives">
                            <h3 class="widget-title">归档</h3>
                                {% archives as date_list %}
                                <ul>
                                    {% for date in date_list %}
                                <li>
                                    <a href="{% url 'blog:archives' date.year date.month %}">
                                        {{ date.year }} 年 {{ date.month }} 月

                                    </a>
                                </li>
                                {% empty %}
                                    暂无归档！
                                {% endfor %}
                                </ul>
                        </div>
                        <div class="widget widget-category">
                            <h3 class="widget-title">分类</h3>
                                {% get_categories as categories %}
                                <ul>
                                    {% for category in categories %}
                                <li>
                                    <a href="{% url 'blog:category' category.pk %}">
                                        {{ category.name }}
                                        <span class="post-count">(13)</span>
                                    </a>
                                </li>
                                    {% empty %}
                                        暂无分类！
                                    {% endfor %}
                                </ul>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-8 col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% block headmessage %} {% endblock %}
                    </div>
                    <div class="panel-body">
                        {% block content %} {% endblock %}

                    </div>
                    <div class="panel-footer">
                        {% include 'footer.html' %}
                    </div>
                    <a href="#top">回到顶部</a><br />
                </div>
            </div>
        </div>
    </div>
    <link rel="stylesheet" href="/static/css/backtop.css">  <!-- Back Top -->
    <script type="text/javascript" src="/static/js/backtop.js"></script>  <!-- Back Top -->
    <div id="back-top">
      <a href="#top" title="回到顶部"></a>
    </div>
</body>
</html>

myblog/templates/footer.html
<!--footer.html-->
{% block footer %}
    {% if now %}
    <p style="font-family: 微软雅黑;" >现在时间：{{ now }}</p>
    {% else %}
    <p style="font-family: 微软雅黑;" >本内容来自网络，如有侵权请来信通知下架……{{ now }}</p>
    {% endif %}
    <hr>
    <p>
        Hi,I am Skyge.Nice to meet you!
    </p>
    <em>
            今日佳句：{{ qoute }}
    </em>
{% endblock %}

myblog/templates/header.html
<!--header.html-->
{% load staticfiles %}

<div class="well";text-align="left">
    <img src="{% static "images/logo.jpg" %}">
    <h2 style="font-family: 微软雅黑">欢迎光临 文学天地</h2>
</div>

myblog/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %} Skyge的博客 {% endblock %}
{% block headmessage %}
    <h3 style="font-family:楷体;">本站文章列表</h3>
{% endblock %}
{% block content %}
    <div class="flex-center">
        <div class="container">
            <div>
                <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
                {% if user.is_authenticated %}
                    <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                    <button class="btn btn-default">
                        <a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                    </button>
                    <button class="btn btn-default">
                        <a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                    </button>
                {% else %}
                    <p>你还没有登录，请
                        <button class="btn btn-default">
                            <a href="{% url 'login' %}?next={{ request.path }}">登录</a>
                        </button>
                        或者
                        <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>

    {%  for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <p style="font-family:微软雅黑;font-size:14pt;font-weight: bold">
                    <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
                </p>
            </div>
            <div class="panel-body" style="background-color: #ffffdd">
                {% if post.id < 7 %}
                    <p >
                        {{ post.text | truncatechars_html:50  }}
                    </p>
                {% else %}
                    <p>
                         {{ post.abstract }}
                    </p>
                {% endif %}

                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">
                        继续阅读 <span class="meta-nav">→</span>
                    </a>
                </div>
            </div>
            <div class="panel-footer" >
                <span class="post-date">
                    <time class="entry-date" datetime="{{ post.created_time }}">
                        {{ post.created_time }}
                    </time>
                </span>
                <div class="entry-meta">
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </div>
        </div>
    {% endfor %}
    {% for archive_list in archives_lists %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <p style="font-family:微软雅黑;font-size:14pt;font-weight: bold">
                    <a href="{{archive_list.get_absolute_url}}">{{ archive_list.title }}</a>
                </p>
            </div>
        </div>
    {% endfor %}
    {% for category_list in category_lists %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <p style="font-family:微软雅黑;font-size:14pt;font-weight: bold">
                    <a href="{{category_list.get_absolute_url}}">{{ category_list.title }}</a>
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}
</body>
</html>

myblog/templates/post.html
<!--post.html-->
{% extends 'base.html' %}
{% block title %} {{ post.title }} - 文学天地 {% endblock %}
{% block headmessage %}
    <h3 style="font-family:微软雅黑;">{{ post.title }}</h3>
{% endblock %}
{% block content %}
    <p style="font-family:微软雅黑;font-size:14pt;font-weight: bold">
        {{ post.text | safe }}
    </p>
    <div class="entry-meta">
        <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
    </div>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                </div>
                <div class="col-md-6">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                </div>
                <button type="submit" class="comment-btn">发表</button>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
                <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                <ul class="comment-list list-unstyled">
                    {% for comment in comment_list %}
                        <li class="comment-item">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date"
                                  datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                            <div class="text">
                                {{ comment.text }}
                            </div>
                        </li>
                    {% empty %}
                        暂无评论
                    {% endfor %}
                </ul>
        </div>
        <div class="entry-meta">
	        <span class="views-count">
	            <a href="{{ post.get_absolute_url }}">本页总访问量{{ post.views }}次</a>
	        </span>
    	</div>
    </section>

{% endblock %}

myblog/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="login.html">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>